[2023-12-24T15:50:49.091+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2023-12-24T15:50:45.948109+00:00 [queued]>
[2023-12-24T15:50:49.095+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2023-12-24T15:50:45.948109+00:00 [queued]>
[2023-12-24T15:50:49.095+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-24T15:50:49.101+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): inaccurate> on 2023-12-24 15:50:45.948109+00:00
[2023-12-24T15:50:49.104+0000] {standard_task_runner.py:60} INFO - Started process 198 to run task
[2023-12-24T15:50:49.106+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2023-12-24T15:50:45.948109+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp_em6bz2x']
[2023-12-24T15:50:49.108+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask inaccurate
[2023-12-24T15:50:49.128+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.inaccurate manual__2023-12-24T15:50:45.948109+00:00 [running]> on host 62d6c974581a
[2023-12-24T15:50:49.158+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-12-24T15:50:45.948109+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-24T15:50:45.948109+00:00'
[2023-12-24T15:50:49.159+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-24T15:50:49.159+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2023-12-24T15:50:49.165+0000] {subprocess.py:86} INFO - Output:
[2023-12-24T15:50:49.166+0000] {subprocess.py:93} INFO - inaccurate
[2023-12-24T15:50:49.167+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-24T15:50:49.177+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20231224T155045, start_date=20231224T155049, end_date=20231224T155049
[2023-12-24T15:50:49.200+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-24T15:50:49.210+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
